"""add emoji to greeting

Revision ID: 7a06a2638015
Revises: 3f4876d2a2dd
Create Date: 2026-05-02 16:57:08.623944

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a06a2638015"
down_revision: str | None = "3f4876d2a2dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("greeting", sa.Column("emoji", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("greeting", "emoji")
    # ### end Alembic commands ###
