"""hello world baseline: greetings table (reference domain for future features)

Revision ID: 3f4876d2a2dd
Revises:
Create Date: 2026-05-01 16:03:37.428058

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f4876d2a2dd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "greeting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("greeting", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_greeting_greeting"), "greeting", ["greeting"], unique=False
    )
    op.create_index(op.f("ix_greeting_name"), "greeting", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_greeting_name"), table_name="greeting")
    op.drop_index(op.f("ix_greeting_greeting"), table_name="greeting")
    op.drop_table("greeting")
    # ### end Alembic commands ###
