"""Initial migration with greeting table

Revision ID: 643b957b6530
Revises:
Create Date: 2025-10-24 01:00:45.286974

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "643b957b6530"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "greeting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("greeting", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_greeting_greeting"), "greeting", ["greeting"], unique=False
    )
    op.create_index(op.f("ix_greeting_name"), "greeting", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_greeting_name"), table_name="greeting")
    op.drop_index(op.f("ix_greeting_greeting"), table_name="greeting")
    op.drop_table("greeting")
    # ### end Alembic commands ###
